version: "3.9"

networks:
  private:
    driver: bridge

services:
  nginx:
    image: nginx:1.27-alpine
    depends_on: [web, grafana]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
    networks: [private]
    security_opt: ["no-new-privileges:true"]
    read_only: true
    tmpfs: [/var/run/nginx,/tmp]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5032"
    volumes:
      - ./Web:/Web:ro
      - /Web/node-modules
    networks: [private]
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]
  
  mosquitto: # MQTT Broker
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883" # MQTTS Only
      - "9001:9001" # WebSockets - will be removed for production
    volumes:
      - ./deploy/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./deploy/mosquitto/acl_files:/mosquitto/config/acl_files:ro
      - ./deploy/secrets/certs:/mosquitto/certs:ro
    networks: [private]
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]
  
  mqttx: # MQTTX Web UI
    image: emqx/mqttx-web:v1.12.1
    container_name: mqttx
    restart: unless-stopped
    ports:
      - "8083:80"
  
  grafana:
    image: grafana/grafana:12.2
    expose:
      - "3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      # - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    networks: [private]
    restart: unless-stopped
    security_opt: ["no-new-privileges:true"]