version: "3.9"

networks:
  private:
    driver: bridge

secrets:
  grafana_admin_user:
    file: ./secrets/grafana/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana/grafana_admin_password.txt
  influx_password:
    file: ./secrets/influx/influx_password.txt
  influx_token:
    file: ./secrets/influx/influx_token.txt
  influx_username:
    file: ./secrets/influx/influx_username.txt

services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - grafana
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./secrets/certs:/secrets/certs:ro
    networks: [private]
    security_opt: ["no-new-privileges:true"]
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run/nginx
      - /run
      - /tmp

  web:
    container_name: datacollectioncloud-web-1
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5032"
    volumes:
      - ./Web:/Web:ro
      - /Web/node-modules
    networks:
      - private
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5032/"]
      interval: 5s
      retries: 10

  mosquitto: # MQTT Broker
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883" # MQTTS Only
      - "9001:9001" # WebSockets - will be removed for production
    volumes:
      - ./deploy/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./deploy/mosquitto/acl_file:/mosquitto/config/acl_file:ro
      - ./secrets/certs:/mosquitto/certs
    networks: [private]
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]

  mqttx: # MQTTX Web UI
    image: emqx/mqttx-web:v1.12.1
    container_name: mqttx
    restart: unless-stopped
    ports:
      - "8083:80"

  grafana:
    image: grafana/grafana:12.2
    expose:
      - "3000"
    environment:
      GF_SERVER_ROOT_URL: https://localhost/grafana/
      GF_SERVE_SERVER_FROM_SUBPATH: true
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE: true
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: /run/secrets/influx_token
      GF_SECURITY_ADMIN_USER: /run/secrets/grafana_admin_user
      GF_SECURITY_ADMIN_PASSWORD: grafana_admin_password
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
    secrets:
      - grafana_admin_user
      - grafana_admin_password
      - influx_token
    networks: [private]
    restart: unless-stopped
    security_opt: ["no-new-privileges:true"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influx_token
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influx_username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influx_password
    volumes:
      - influxdb_data:/var/lib/influxdb2
    secrets:
      - influx_password
      - influx_token
      - influx_username
    networks: [private]
    security_opt: ["no-new-privileges:true"]

volumes:
  influxdb_data:
