version: "3.9"

networks:
  private:
    driver: bridge

secrets:
  grafana_admin_user:
    file: ./secrets/grafana/grafana_admin_user.txt
  grafana_admin_password:
    file: ./secrets/grafana/grafana_admin_password.txt
  influx_bucket:
    file: ./secrets/influx/influx_bucket.txt
  influx_org:
    file: ./secrets/influx/influx_org.txt
  influx_password:
    file: ./secrets/influx/influx_password.txt
  influx_token:
    file: ./secrets/influx/influx_token.txt
  influx_username:
    file: ./secrets/influx/influx_username.txt
  influx_url:
    file: ./secrets/influx/influx_url.txt
  mosquitto_broker:
    file: ./secrets/mosquitto/mosquitto_broker.txt
  mosquitto_topic_1:
    file: ./secrets/mosquitto/mosquitto_topic_1.txt
  mosquitto_topic_2:
    file: ./secrets/mosquitto/mosquitto_topic_2.txt
  mosquitto_topic_prefix:
    file: ./secrets/mosquitto/mosquitto_topic_prefix.txt
  postgres_user:
    file: ./secrets/postgres/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres/postgres_password.txt
  postgres_db:
    file: ./secrets/postgres/postgres_db.txt
  postgres_url:
    file: ./secrets/postgres/postgres_url.txt
  postgres_port:
    file: ./secrets/postgres/postgres_port.txt

services:
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - grafana
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./secrets/certs:/secrets/certs:ro
    networks: [private]
    security_opt: ["no-new-privileges:true"]
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run/nginx
      - /run
      - /tmp

  web:
    container_name: datacollectioncloud-web-1
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5032"
    depends_on:
      postgres:
        condition: service_healthy
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - postgres_url
      - postgres_port
      - influx_username
      - influx_password
      - influx_token
      - influx_bucket
      - influx_org
      - influx_url
      - mosquitto_broker
      - mosquitto_topic_1
      - mosquitto_topic_2
      - mosquitto_topic_prefix
    volumes:
      - ./Web:/Web:ro
      - /node-modules
    networks:
      - private
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]
    environment:
      INFLUX_TOKEN_FILE: /run/secrets/influx_token
      INFLUX_USERNAME_FILE: /run/secrets/influx_username
      INFLUX_PASSWORD_FILE: /run/secrets/influx_password
      INFLUX_ORG_FILE: /run/secrets/influx_org
      INFLUX_BUCKET_FILE: /run/secrets/influx_bucket
      INFLUX_URL_FILE: /run/secrets/influx_url
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_URL_FILE: /run/secrets/postgres_url
      POSTGRES_PORT_FILE: /run/secrets/postgres_port
      MOSQUITTO_BROKER_FILE: /run/secrets/mosquitto_broker
      MOSQUITTO_TOPIC_1_FILE: /run/secrets/mosquitto_topic_1
      MOSQUITTO_TOPIC_2_FILE: /run/secrets/mosquitto_topic_2
      MOSQUITTO_TOPIC_PREFIX_FILE: /run/secrets/mosquitto_topic_prefix
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5032/"]
      interval: 5s
      retries: 10

  mosquitto: # MQTT Broker
    image: eclipse-mosquitto:2.0.22
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883" # MQTTS Only
      - "9001:9001" # WebSockets - will be removed for production
    volumes:
      - ./deploy/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./deploy/mosquitto/acl_file:/mosquitto/config/acl_file:ro
      - ./secrets/certs:/mosquitto/certs
    networks: [private]
    tmpfs: [/tmp]
    security_opt: ["no-new-privileges:true"]

  mqttx: # MQTTX Web UI
    image: emqx/mqttx-web:v1.12.1
    container_name: mqttx
    restart: unless-stopped
    ports:
      - "8083:80"

  grafana:
    image: grafana/grafana:12.2
    expose:
      - "3000"
    environment:
      GF_SERVER_ROOT_URL: https://grafana:3000/grafana
      GF_SERVE_SERVER_FROM_SUBPATH: true
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_CHANGE: true
      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password

      # Allow unsigned plugins and preinstall them
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-metricsdrilldown-app,yesoreyeram-infinity-datasource
      GF_PLUGINS_PREINSTALL: yesoreyeram-infinity-datasource
    entrypoint:
      - /bin/sh
      - -c
      - |
        export INFLUX_TOKEN=$(cat /run/secrets/influx_token)
        export INFLUX_URL=$(cat /run/secrets/influx_url)
        export INFLUX_USERNAME=$(cat /run/secrets/influx_username)
        export POSTGRES_URL=$(cat /run/secrets/postgres_url)
        export POSTGRES_USER=$(cat /run/secrets/postgres_user)
        export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password)
        export POSTGRES_DB=$(cat /run/secrets/postgres_db)
        exec /run.sh
    depends_on:
      - influxdb
      - postgres
    secrets:
      - grafana_admin_user
      - grafana_admin_password
      - influx_token
      - influx_url
      - influx_username
      - postgres_url
      - postgres_password
      - postgres_db
      - postgres_user
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana-provisioning/:/etc/grafana/provisioning:ro
    networks: [private]
    restart: unless-stopped
    security_opt: ["no-new-privileges:true"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:                    # TODO: make this an "expose" and run it inside nginx
      - "8086:8086"
    secrets:
      - influx_password
      - influx_token
      - influx_username
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: myorg
      DOCKER_INFLUXDB_INIT_BUCKET: mybucket
      INFLUXDB_ENABLE_INFLUXQL: yes
      INFLUXDB_ENABLE_INFLUXQL_AUTH: yes
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influx_token
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influx_username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influx_password
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks: [private]
    security_opt: ["no-new-privileges:true"]

  postgres:
    container_name: postgres
    image: postgres:18.1
    expose:
      - "5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      PGDATA: /var/lib/postgresql
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    volumes:
      - postgres_data:/data/postgres
      - ./deploy/postgres/create-db.sql:/docker-entrypoint-initdb.d/create_database.sql:ro
    networks: [private]
    security_opt: ["no-new-privileges:true"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) -d $(cat /run/secrets/postgres_db)"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  influxdb_data:
  postgres_data:
  grafana-data:
