apiVersion: 1

datasources:
  - name: InfluxDB - new provisioned
    type: influxdb
    access: proxy
    url: ${DOCKER_INFLUX_URL}
    isDefault: true
    editable: true
    jsonData:
      version: SQL
      organization: myorg
      defaultBucket: mybucket
    secureJsonData:
      token: ${INFLUX_TOKEN}
    basicAuth: false