apiVersion: 1

datasources:
  - name: InfluxDB - new provisioned
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      organization: myorg
      defaultBucket: mybucket
      httpMode: api
      # Grafana requires this for InfluxQL:
      database: mybucket
      retentionPolicy: ""
    secureJsonData:
      token: ${INFLUX_TOKEN}
    basicAuth: false
