apiVersion: 1

datasources:
  - name: InfluxDB - new provisioned
    type: influxdb
    access: proxy
    url: ${INFLUX_URL}
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      dbName: mybucket
      httpHeaderName1: 'Authorization'
      retentionPolicy: ""
    secureJsonData:
      httpHeaderValue1: 'Token ${INFLUX_TOKEN}'
    basicAuth: true
